### ISSUE TITLE
Fail to upgrade

### ISSUE THREAD

**Issue by Doude** [YunoHost-Apps/kresus_ynh#35]
I cannot upgrade kresus app from `0.13.3~ynh1` to `0.13.3~ynh2`, it fails to create the python virtuenv as it is already existing:

```
58306 DEBUG + virtualenv --system-site-packages /var/www/kresus/venv
58908 DEBUG New python executable in /var/www/kresus/venv/bin/python2
58908 WARNING Traceback (most recent call last):
58909 DEBUG Not overwriting existing python script /var/www/kresus/venv/bin/python (you must use /var/www/kresus/venv/bin/python2)
58910 WARNING   File "/usr/lib/python3/dist-packages/virtualenv.py", line 2375, in <module>
58910 DEBUG Running virtualenv with interpreter /usr/bin/python2
58910 WARNING     main()
58910 WARNING   File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
58911 WARNING     symlink=options.symlink)
58911 WARNING   File "/usr/lib/python3/dist-packages/virtualenv.py", line 946, in create_environment
58911 WARNING     site_packages=site_packages, clear=clear, symlink=symlink))
58911 WARNING   File "/usr/lib/python3/dist-packages/virtualenv.py", line 1417, in install_python
58912 WARNING     os.symlink(py_executable_base, full_pth)
58912 WARNING OSError: [Errno 17] File exists
59014 DEBUG + ynh_exit_properly
59014 DEBUG + local exit_code=1
59015 DEBUG + '[' 1 -eq 0 ']'
59015 DEBUG + trap '' EXIT
59015 DEBUG + set +eu
59015 DEBUG + sleep 0.5
59517 DEBUG + ynh_print_err '--message=!!\n  kresus'\''s script has encountered an error. Its execution was cancelled.\n!!'
```

I'm using yunohost version:
```
yunohost:
  repo: stable
  version: 3.6.4.3
yunohost-admin:
  repo: stable
  version: 3.6.4
moulinette:
  repo: stable
  version: 3.6.4
ssowat:
  repo: stable
  version: 3.6.4
```
