### ISSUE TITLE
Upgrade to Kresus 0.16 

### ISSUE THREAD

**Issue by flera** [YunoHost-Apps/kresus_ynh#57]
Hello,
After a toot on mastodon, I hurried to update kresus.
2 errors:
- the postgres user is missing. I manually create it and relaunch the upgrade
- I don't understand the second error, here are the logs : 
https://paste.yunohost.org/foqutadova.bash

Kresus is still working and my data are ok.

i'm using a virtual machine to use yunohost.

Thanks for your work

**Comment by Jibec** [comment]
hello, thanks for the feedback, the postgres user not existing is weird, it should come from Debian itself.
Creating it manually hide the rootcause.

How up to date is your debian? Please sure more context.

**Comment by flera** [comment]
I just update my yunohost to 3.7.1.3 yesterday, and today, i try to upgrade kresus.

I did not install myself postgresql.

**Comment by Jibec** [comment]
ok, can you please provide the error log with the postgres user missing? it should be in your installtion history

**Comment by flera** [comment]
Here they are :
https://paste.yunohost.org/opohejodep.lua

**Comment by Jibec** [comment]
Weird, it says postgresql shoud be 9.4 or 9.6
What version of Debian and Postgresql do you have?

**Comment by SiM** [comment]
Hello,
It seems I have the same error here : https://paste.yunohost.org/raw/ugeyijobaj

Debian version : 9.12
Postgresql is not installed

```
# yunohost --version
yunohost:
  repo: stable
  version: 3.7.1.3
yunohost-admin:
  repo: stable
  version: 3.7.1.1
moulinette:
  repo: stable
  version: 3.7.1.1
ssowat:
  repo: stable
  version: 3.7.1.1

```
