### ISSUE TITLE
Cannot access Kresus after upgrade to 0.17.2 : please install weboob

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/kresus_ynh#98]
Hi,
After upgrading Kresus to 0.17.2 (the upgrade was successful), when I try to open Kresus (_mydomain.tld/kresus_), I'm redirected to a page (_mydomain.tld/#/weboob-readme_) which tell me that I need to install Weboob version 2 or greater. 
Here is the full message (it's in french):

> Veuillez installer Weboob en version 2.0 ou supérieure
> Afin de fonctionner, Kresus a besoin d'une dépendance unique, Weboob. Kresus n'a pu détecter d'installation fonctionnelle de Weboob (Weboob ou une de ses dépendances n'est pas installé correctement). Pour vous offrir la meilleure expérience possible, il est nécessaire que Weboob soit installé en version stable (2.0 à ce jour) ou expérimentale. Contactez l'administrateur de votre Kresus en lui demandant d'installer Weboob manuellement, comme indiqué dans le fichier README : README 

---

```
yunohost: 
  repo: stable
  version: 4.1.8
yunohost-admin: 
  repo: stable
  version: 4.1.4
moulinette: 
  repo: stable
  version: 4.1.4
ssowat: 
  repo: stable
  version: 4.1.3
```
